// <auto-generated />
using System;
using MessengerService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MessengerService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    partial class MessagingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("messenger")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MessengerService.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CurrentSequence")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("current_sequence");

                    b.Property<long?>("DirectUserHighId")
                        .HasColumnType("bigint")
                        .HasColumnName("direct_user_high_id");

                    b.Property<long?>("DirectUserLowId")
                        .HasColumnType("bigint")
                        .HasColumnName("direct_user_low_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_conversations_updated_at");

                    b.HasIndex("DirectUserLowId", "DirectUserHighId")
                        .IsUnique()
                        .HasDatabaseName("ux_conversations_direct_pair")
                        .HasFilter("type = 'Direct'");

                    b.ToTable("conversations", "messenger", t =>
                        {
                            t.HasCheckConstraint("ck_conversations_current_sequence", "current_sequence >= 0");

                            t.HasCheckConstraint("ck_conversations_direct_pair", "(type = 'Direct' AND direct_user_low_id IS NOT NULL AND direct_user_high_id IS NOT NULL AND direct_user_low_id > 0 AND direct_user_low_id < direct_user_high_id) OR (type = 'Group' AND direct_user_low_id IS NULL AND direct_user_high_id IS NULL)");

                            t.HasCheckConstraint("ck_conversations_type", "type IN ('Direct', 'Group')");

                            t.HasCheckConstraint("ck_conversations_updated_at", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("MessengerService.Domain.Entities.ConversationParticipant", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<long>("LastDeliveredSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("last_delivered_sequence");

                    b.Property<long>("LastReadSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("last_read_sequence");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("ConversationId", "UserId")
                        .HasName("pk_conversation_participants");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_conversation_participants_active_conversation")
                        .HasFilter("left_at IS NULL");

                    b.HasIndex("UserId", "ConversationId")
                        .HasDatabaseName("ix_conversation_participants_active_user")
                        .HasFilter("left_at IS NULL");

                    b.ToTable("conversation_participants", "messenger", t =>
                        {
                            t.HasCheckConstraint("ck_conversation_participants_membership_dates", "left_at IS NULL OR left_at >= joined_at");

                            t.HasCheckConstraint("ck_conversation_participants_receipts", "last_delivered_sequence >= 0 AND last_read_sequence >= 0 AND last_read_sequence <= last_delivered_sequence");

                            t.HasCheckConstraint("ck_conversation_participants_role", "role IN ('Admin', 'Member')");

                            t.HasCheckConstraint("ck_conversation_participants_user_id", "user_id > 0");
                        });
                });

            modelBuilder.Entity("MessengerService.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_message_id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<Guid?>("ReplyToMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("reply_to_message_id");

                    b.Property<long>("SenderUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_user_id");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("Text")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ReplyToMessageId")
                        .HasDatabaseName("ix_messages_reply_to_message_id");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique()
                        .IsDescending(false, true)
                        .HasDatabaseName("ux_messages_conversation_sequence");

                    b.HasIndex("SenderUserId", "ClientMessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_messages_sender_client_message");

                    b.ToTable("messages", "messenger", t =>
                        {
                            t.HasCheckConstraint("ck_messages_client_message_id", "client_message_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_messages_delete_date", "deleted_at IS NULL OR deleted_at >= created_at");

                            t.HasCheckConstraint("ck_messages_edit_date", "edited_at IS NULL OR edited_at >= created_at");

                            t.HasCheckConstraint("ck_messages_sender_user_id", "sender_user_id > 0");

                            t.HasCheckConstraint("ck_messages_sequence", "sequence > 0");
                        });
                });

            modelBuilder.Entity("MessengerService.Domain.Entities.MessageAttachment", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("MessageId", "Ordinal")
                        .HasName("pk_message_attachments");

                    b.ToTable("message_attachments", "messenger", t =>
                        {
                            t.HasCheckConstraint("ck_message_attachments_https_url", "url LIKE 'https://%'");

                            t.HasCheckConstraint("ck_message_attachments_ordinal", "ordinal >= 0 AND ordinal < 10");
                        });
                });

            modelBuilder.Entity("MessengerService.Domain.Entities.MessageReaction", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("emoji");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MessageId", "UserId")
                        .HasName("pk_message_reactions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_message_reactions_user_id");

                    b.ToTable("message_reactions", "messenger", t =>
                        {
                            t.HasCheckConstraint("ck_message_reactions_emoji", "length(btrim(emoji)) > 0");

                            t.HasCheckConstraint("ck_message_reactions_updated_at", "updated_at >= created_at");

                            t.HasCheckConstraint("ck_message_reactions_user_id", "user_id > 0");
                        });
                });

            modelBuilder.Entity("MessengerService.Domain.Entities.MessagingUser", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.ToTable("users", "messenger", t =>
                        {
                            t.HasCheckConstraint("ck_users_deleted_state", "(status = 'Active' AND deleted_at IS NULL) OR (status = 'Deleted' AND deleted_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_users_status", "status IN ('Active', 'Deleted')");

                            t.HasCheckConstraint("ck_users_user_id_positive", "user_id > 0");
                        });
                });

            modelBuilder.Entity("MessengerService.Domain.Entities.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<long?>("SubjectUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("subject_user_id");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_events");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_events_processed")
                        .HasFilter("processed_at IS NOT NULL");

                    b.HasIndex("NextAttemptAt", "CreatedAt")
                        .HasDatabaseName("ix_outbox_events_pending")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("Topic", "CreatedAt")
                        .HasDatabaseName("ix_outbox_events_pending_topic")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_events", "messenger", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_events_actor_user_id", "actor_user_id IS NULL OR actor_user_id > 0");

                            t.HasCheckConstraint("ck_outbox_events_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_outbox_events_sequence", "sequence IS NULL OR sequence >= 0");

                            t.HasCheckConstraint("ck_outbox_events_subject_user_id", "subject_user_id IS NULL OR subject_user_id > 0");
                        });
                });

            modelBuilder.Entity("MessengerService.Domain.Entities.UserPresence", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_presence");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_presence_online_expiry")
                        .HasFilter("is_online = TRUE");

                    b.ToTable("presence", "messenger", t =>
                        {
                            t.HasCheckConstraint("ck_presence_user_id", "user_id > 0");
                        });
                });

            modelBuilder.Entity("MessengerService.Domain.Entities.ConversationParticipant", b =>
                {
                    b.HasOne("MessengerService.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_participants_conversations");

                    b.HasOne("MessengerService.Domain.Entities.MessagingUser", "User")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_participants_users");

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessengerService.Domain.Entities.Message", b =>
                {
                    b.HasOne("MessengerService.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations");

                    b.HasOne("MessengerService.Domain.Entities.Message", "ReplyToMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_messages_reply_to_message");

                    b.HasOne("MessengerService.Domain.Entities.MessagingUser", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users");

                    b.Navigation("Conversation");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MessengerService.Domain.Entities.MessageAttachment", b =>
                {
                    b.HasOne("MessengerService.Domain.Entities.Message", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_attachments_messages");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MessengerService.Domain.Entities.MessageReaction", b =>
                {
                    b.HasOne("MessengerService.Domain.Entities.Message", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_reactions_messages");

                    b.HasOne("MessengerService.Domain.Entities.MessagingUser", "User")
                        .WithMany("MessageReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_message_reactions_users");

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessengerService.Domain.Entities.UserPresence", b =>
                {
                    b.HasOne("MessengerService.Domain.Entities.MessagingUser", "User")
                        .WithOne("Presence")
                        .HasForeignKey("MessengerService.Domain.Entities.UserPresence", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_presence_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessengerService.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("MessengerService.Domain.Entities.Message", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("MessengerService.Domain.Entities.MessagingUser", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("MessageReactions");

                    b.Navigation("Presence");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
